### ISSUE TITLE
Bug?: Cannot read property 'host' of null

### ISSUE THREAD

**Issue by Mr-Smarty** [PassTheMayo/Minecraft-Ping#11]
Used minecraft-server-util + discord.js with this code to ping a server and put the info into an embed:
```javascript       
       ping('74.99.66.137', 25565, (error, response) => {
            if (error) {
                const errorEmbed = new Discord.MessageEmbed()
                .setTitle('Server Status')
                .setColor(info.embedHexcode)
                .setDescription('Offline :pensive: Contact Cdub#5909')
                .setTimestamp()
                message.channel.send(errorEmbed);
            }
            
            const serverEmbed = new Discord.MessageEmbed()
            .setTitle('Server Status')
            .setColor(info.embedHexcode)
            .setDescription('Online! :thumbsup:')
            .addField('Server IP', response.host)
            .addField('Server Version', response.version)
            .addField('Online Players', response.onlinePlayers + '\n' + '\n Use `=players` to view online players')
            .addField('Server Description', response.descriptionText)
            .setTimestamp()
            message.channel.send(serverEmbed);
         
            console.log(response);
        });
```
and got this error:
```
(node:9928) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'host' of null
    at C:\Users\Tamar\Desktop\BTE Bot\node_modules\minecraft-server-util\src\index.js:138:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Then checked server myself using minecraft, saw it was online, restarted the bot, and then it worked without changing any code.
Please note I am relatively new to javascript and github :)

**Comment by PassTheMayo** [comment]
This bug appears to be a problem on your end, not with the library. In your error checking code, make sure to `return` so the remaining code does not continue if there's an error. The `response` variable will be null if there are any errors.

**Comment by Mr-Smarty** [comment]
Ahh... That makes a lot of sense. I completely forgot about `return`. Thankyou so much for the help, and thankyou for bearing with my lack of knowledge :) I am slowly learning...
